In [14]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
import pandas as pd

# 数据无量纲化

## 归一化

In [3]:
data=[[-1,2],[-0.5,6],[0,10],[1,18]]
pd.DataFrame(data)

#实现归一化
scaler=MinMaxScaler() #实例化
scaler=scaler.fit(data)#fit,在这里本质是生成min(x)和max(x)
result=scaler.transform(data)#通过接口导出结果

In [4]:
pd.DataFrame(data)

0   1
0 -1.0   2
1 -0.5   6
2  0.0  10
3  1.0  18

In [8]:
pd.DataFrame(result)

0     1
0  0.00  0.00
1  0.25  0.25
2  0.50  0.50
3  1.00  1.00

In [9]:
pd.DataFrame(scaler.inverse_transform(result))#将归一化后的结果逆转

0     1
0 -1.0   2.0
1 -0.5   6.0
2  0.0  10.0
3  1.0  18.0

## 标准化

In [10]:
data=[[-1,2],[-0.5,6],[0,10],[1,18]]
pd.DataFrame(data)

#实现归一化
scaler=StandardScaler() #实例化
scaler=scaler.fit(data)#fit,在这里本质是生成min(x)和max(x)
result=scaler.transform(data)#通过接口导出结果

In [11]:
pd.DataFrame(data)

0   1
0 -1.0   2
1 -0.5   6
2  0.0  10
3  1.0  18

In [12]:
pd.DataFrame(result)

0         1
0 -1.183216 -1.183216
1 -0.507093 -0.507093
2  0.169031  0.169031
3  1.521278  1.521278

In [13]:
pd.DataFrame(scaler.inverse_transform(result))#将归一化后的结果逆转

0     1
0 -1.0   2.0
1 -0.5   6.0
2  0.0  10.0
3  1.0  18.0

# 缺失值处理

## sklearn.simpleImputer

In [16]:
data = pd.read_csv('./data/Narrativedata.csv',index_col=0)
data.head()

Unnamed: 0   Age     Sex Embarked Survived
0           0  22.0    male        S       No
1           1  38.0  female        C      Yes
2           2  26.0  female        S      Yes
3           3  35.0  female        S      Yes
4           4  35.0    male        S       No

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  891 non-null    int64  
 1   Age         714 non-null    float64
 2   Sex         891 non-null    object 
 3   Embarked    889 non-null    object 
 4   Survived    891 non-null    object 
dtypes: float64(1), int64(1), object(3)
memory usage: 34.9+ KB


In [19]:
Age = data.loc[:,'Age'].values.reshape(-1, 1) # sklearn 处理特征必须是二维的
Age[:20]

array([[22.],
       [38.],
       [26.],
       [35.],
       [35.],
       [nan],
       [54.],
       [ 2.],
       [27.],
       [14.],
       [ 4.],
       [58.],
       [20.],
       [39.],
       [14.],
       [55.],
       [ 2.],
       [nan],
       [31.],
       [nan]])

In [20]:
imp_mean = SimpleImputer()
imp_median = SimpleImputer(strategy='median')
imp_0 = SimpleImputer(strategy='constant', fill_value=0)

In [23]:
# imp_mean_model = imp_mean.fit(Age)
# imp_mean_result = imp_mean_model.transform(Age)
imp_mean_result = imp_mean.fit_transform(Age)
imp_mean_result

array([[22.        ],
       [38.        ],
       [26.        ],
       [35.        ],
       [35.        ],
       [29.69911765],
       [54.        ],
       [ 2.        ],
       [27.        ],
       [14.        ],
       [ 4.        ],
       [58.        ],
       [20.        ],
       [39.        ],
       [14.        ],
       [55.        ],
       [ 2.        ],
       [29.69911765],
       [31.        ],
       [29.69911765],
       [35.        ],
       [34.        ],
       [15.        ],
       [28.        ],
       [ 8.        ],
       [38.        ],
       [29.69911765],
       [19.        ],
       [29.69911765],
       [29.69911765],
       [40.        ],
       [29.69911765],
       [29.69911765],
       [66.        ],
       [28.        ],
       [42.        ],
       [29.69911765],
       [21.        ],
       [18.        ],
       [14.        ],
       [40.        ],
       [27.        ],
       [29.69911765],
       [ 3.        ],
       [19.        ],
       [29

In [24]:
imp_median_result = imp_median.fit_transform(Age)
imp_median_result

array([[22.  ],
       [38.  ],
       [26.  ],
       [35.  ],
       [35.  ],
       [28.  ],
       [54.  ],
       [ 2.  ],
       [27.  ],
       [14.  ],
       [ 4.  ],
       [58.  ],
       [20.  ],
       [39.  ],
       [14.  ],
       [55.  ],
       [ 2.  ],
       [28.  ],
       [31.  ],
       [28.  ],
       [35.  ],
       [34.  ],
       [15.  ],
       [28.  ],
       [ 8.  ],
       [38.  ],
       [28.  ],
       [19.  ],
       [28.  ],
       [28.  ],
       [40.  ],
       [28.  ],
       [28.  ],
       [66.  ],
       [28.  ],
       [42.  ],
       [28.  ],
       [21.  ],
       [18.  ],
       [14.  ],
       [40.  ],
       [27.  ],
       [28.  ],
       [ 3.  ],
       [19.  ],
       [28.  ],
       [28.  ],
       [28.  ],
       [28.  ],
       [18.  ],
       [ 7.  ],
       [21.  ],
       [49.  ],
       [29.  ],
       [65.  ],
       [28.  ],
       [21.  ],
       [28.5 ],
       [ 5.  ],
       [11.  ],
       [22.  ],
       [38.  ],
       [

In [25]:
imp_0_result = imp_0.fit_transform(Age)
imp_0_result

array([[22.  ],
       [38.  ],
       [26.  ],
       [35.  ],
       [35.  ],
       [ 0.  ],
       [54.  ],
       [ 2.  ],
       [27.  ],
       [14.  ],
       [ 4.  ],
       [58.  ],
       [20.  ],
       [39.  ],
       [14.  ],
       [55.  ],
       [ 2.  ],
       [ 0.  ],
       [31.  ],
       [ 0.  ],
       [35.  ],
       [34.  ],
       [15.  ],
       [28.  ],
       [ 8.  ],
       [38.  ],
       [ 0.  ],
       [19.  ],
       [ 0.  ],
       [ 0.  ],
       [40.  ],
       [ 0.  ],
       [ 0.  ],
       [66.  ],
       [28.  ],
       [42.  ],
       [ 0.  ],
       [21.  ],
       [18.  ],
       [14.  ],
       [40.  ],
       [27.  ],
       [ 0.  ],
       [ 3.  ],
       [19.  ],
       [ 0.  ],
       [ 0.  ],
       [ 0.  ],
       [ 0.  ],
       [18.  ],
       [ 7.  ],
       [21.  ],
       [49.  ],
       [29.  ],
       [65.  ],
       [ 0.  ],
       [21.  ],
       [28.5 ],
       [ 5.  ],
       [11.  ],
       [22.  ],
       [38.  ],
       [

In [26]:
# 使用中位数填充 Age
data.loc[:,"Age"]=imp_median
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  891 non-null    int64 
 1   Age         891 non-null    object
 2   Sex         891 non-null    object
 3   Embarked    889 non-null    object
 4   Survived    891 non-null    object
dtypes: int64(1), object(4)
memory usage: 34.9+ KB


In [27]:
#使用众数填补Embarked,众数可以填充文字型数据
Embarked=data.loc[:,"Embarked"].values.reshape(-1,1)
imp_mode=SimpleImputer(strategy="most_frequent")
data.loc[:,"Embarked"]=imp_mode.fit_transform(Embarked)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  891 non-null    int64 
 1   Age         891 non-null    object
 2   Sex         891 non-null    object
 3   Embarked    891 non-null    object
 4   Survived    891 non-null    object
dtypes: int64(1), object(4)
memory usage: 34.9+ KB


## 使用 pandas numpy

In [58]:
data = pd.read_csv('./data/Narrativedata.csv',index_col=0)
data.head()

Age     Sex Embarked Survived
0  22.0    male        S       No
1  38.0  female        C      Yes
2  26.0  female        S      Yes
3  35.0  female        S      Yes
4  35.0    male        S       No

In [29]:
data.loc[:,"Age"]=data.loc[:,"Age"].fillna(data.loc[:,"Age"].median())
data

Unnamed: 0   Age     Sex Embarked Survived
0             0  22.0    male        S       No
1             1  38.0  female        C      Yes
2             2  26.0  female        S      Yes
3             3  35.0  female        S      Yes
4             4  35.0    male        S       No
..          ...   ...     ...      ...      ...
886         886  27.0    male        S       No
887         887  19.0  female        S      Yes
888         888  28.0  female        S       No
889         889  26.0    male        C  Unknown
890         890  32.0    male        Q       No

[891 rows x 5 columns]

In [30]:
data.dropna(axis=0,inplace=True)
#.dropna(axis=0)删除所有有缺失值的行，.dropna(axis=1)删除所有有缺失值的列
#参数inplace=True表示在原数据集上进行修改，为False表示生成一个复制对象，不修改原数据，默认为False
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 889 entries, 0 to 890
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  889 non-null    int64  
 1   Age         889 non-null    float64
 2   Sex         889 non-null    object 
 3   Embarked    889 non-null    object 
 4   Survived    889 non-null    object 
dtypes: float64(1), int64(1), object(3)
memory usage: 41.7+ KB


## 处理分类型特征：编码与哑变量

### 标签

In [59]:
from sklearn.preprocessing import LabelEncoder#标签专用

data = pd.read_csv('./data/Narrativedata.csv',index_col=0)

#index_col意思是把第0列作为索引
y=data.iloc[:,-1]#要输入的是标签，不是特征矩阵，所有允许一维（一般都习惯放到最后一列，这里是survived  ）

le=LabelEncoder()#实例化
le=le.fit(y)#导入数据
label=le.transform(y)#transfrom接口调取结果

# data.iloc[:,-1]=LabelEncoder().fit_transform(data.iloc[:,-1])

In [60]:
le.classes_ # 查看标签类别

array(['No', 'Unknown', 'Yes'], dtype=object)

In [61]:
data.iloc[:,-1]=label#让标签等于我们运行出来的结果

### 特征

In [62]:
from sklearn.preprocessing import OrdinalEncoder

data_ = data.copy()

data_.loc[:,"Age"]=data_.loc[:,"Age"].fillna(data_.loc[:,"Age"].median())
data_.dropna(axis=0,inplace=True)

#需要保证没有缺失值，如果有缺失值，则会报错
OrdinalEncoder().fit(data_.iloc[:,1:-1]).categories_#data_.iloc[:,1:-1]所有的行从索引为1的列取到最后1列（不包括最后1列）

[array(['female', 'male'], dtype=object), array(['C', 'Q', 'S'], dtype=object)]

In [63]:
data_.iloc[:,1:-1]=OrdinalEncoder().fit_transform(data_.iloc[:,1:-1])

In [64]:
data_

Age  Sex  Embarked  Survived
0    22.0  1.0       2.0         0
1    38.0  0.0       0.0         2
2    26.0  0.0       2.0         2
3    35.0  0.0       2.0         2
4    35.0  1.0       2.0         0
..    ...  ...       ...       ...
886  27.0  1.0       2.0         0
887  19.0  0.0       2.0         2
888  28.0  0.0       2.0         0
889  26.0  1.0       0.0         1
890  32.0  1.0       1.0         0

[889 rows x 4 columns]

### 使用独热编码，创建哑变量

In [68]:
from sklearn.preprocessing import OneHotEncoder

X = data.iloc[:,1:-1]
X.dropna(axis=0,inplace=True)
enc = OneHotEncoder(categories='auto').fit(X)
result = enc.transform(X).toarray()#转化为数组
# # enc.transform(X)
result#因为是sex和embarked两个特征，sex有两类，embarked有三类，所以最后结果是5列

array([[0., 1., 0., 0., 1.],
       [1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1.],
       ...,
       [1., 0., 0., 0., 1.],
       [0., 1., 1., 0., 0.],
       [0., 1., 0., 1., 0.]])

In [70]:
enc.get_feature_names()

array(['x0_female', 'x0_male', 'x1_C', 'x1_Q', 'x1_S'], dtype=object)

In [76]:
new_data =pd.concat([data, pd.DataFrame(result)], axis=1)
new_data.drop(['Sex', 'Embarked'], axis=1, inplace=True)
new_data.columns = ['Age','Survived', 'x0_female', 'x0_male', 'x1_C', 'x1_Q', 'x1_S']

In [77]:
new_data

Age  Survived  x0_female  x0_male  x1_C  x1_Q  x1_S
0    22.0         0        0.0      1.0   0.0   0.0   1.0
1    38.0         2        1.0      0.0   1.0   0.0   0.0
2    26.0         2        1.0      0.0   0.0   0.0   1.0
3    35.0         2        1.0      0.0   0.0   0.0   1.0
4    35.0         0        0.0      1.0   0.0   0.0   1.0
..    ...       ...        ...      ...   ...   ...   ...
886  27.0         0        1.0      0.0   0.0   0.0   1.0
887  19.0         2        0.0      1.0   1.0   0.0   0.0
888   NaN         0        0.0      1.0   0.0   1.0   0.0
889  26.0         1        NaN      NaN   NaN   NaN   NaN
890  32.0         0        NaN      NaN   NaN   NaN   NaN

[891 rows x 7 columns]

### 处理连续型特征，二值化和分段

#### 二值化

In [78]:
from sklearn.preprocessing import Binarizer

In [80]:
data_2=data.copy()
data_2.dropna(axis=0,inplace=True)

X = data_2.iloc[:,0].values.reshape(-1,1)#Binarizer类为特征专用，所以不能使用一维数组
transformer=Binarizer(threshold=30).fit_transform(X)#30以上的划为1，以下的划为0
#transformer

data_2.iloc[:,0]=transformer

In [81]:
data_2

Age     Sex Embarked  Survived
0    0.0    male        S         0
1    1.0  female        C         2
2    0.0  female        S         2
3    1.0  female        S         2
4    1.0    male        S         0
..   ...     ...      ...       ...
885  1.0  female        Q         0
886  0.0    male        S         0
887  0.0  female        S         2
889  0.0    male        C         1
890  1.0    male        Q         0

[712 rows x 4 columns]

#### 分段

In [83]:
from sklearn.preprocessing import KBinsDiscretizer

In [85]:
data_3=data.copy()
data_3.dropna(axis=0,inplace=True)

X = data_3.iloc[:,0].values.reshape(-1,1)
est = KBinsDiscretizer(n_bins=3,encode='ordinal',strategy='uniform')
est.fit_transform(X)

array([[0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [2.],
       [0.],
       [1.],
       [0.],
       [0.],
       [2.],
       [0.],
       [1.],
       [0.],
       [2.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [2.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [2.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [2.],
       [2.],
       [0.],
       [1.],
       [1.],